#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '❌ 🎨 Prettier Check Failed. Run npm run format, add changes and try committing again. 🎨 ❌';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '❌ 🤵 ESLint Check Failed. Make the changes required above and try committing again. 🤵 ❌'
        false; 
)


# If everything passes... Now we can commit
echo '✅ ✅Your checked-in code looks good. Commiting... ✅ ✅'